# Generated by Django 4.2.9 on 2025-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_contratacion', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto del empleado')),
            ],
        ),
    ]
