# Generated by Django 4.2.9 on 2025-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cdula',
            field=models.CharField(default=31158004, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
