# Generated by Django 4.2.9 on 2025-07-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado_cdula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cdula',
            field=models.CharField(max_length=15),
        ),
    ]
