# Generated by Django 4.2.9 on 2025-07-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_alter_empleado_cdula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='cdula',
            new_name='cedula',
        ),
    ]
